services:
  - docker

language: python

sudo: required
  
branches:
  only:
    - master

before_install:
  - wget https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-linux-amd64-2.1.1.tar.gz
  - tar xvzf git-lfs-linux-amd64-2.1.1.tar.gz
  - sudo ./git-lfs-2.1.1/install.sh
  - git lfs fetch
  - docker pull veros/ubuntu:16.04

install:
  - docker build -t veros -f package/docker/testing.dockerfile .

env:
  global:
    - PYOM_DIR=/pyOM2/py_src
    - TEST_DIR=/veros/test
  matrix:
    - PYTHON_EXEC=python2 PYOM_LIB=pyOM_code_py2.so PYOM_MPI_LIB=pyOM_code_MPI_py2.so
    - PYTHON_EXEC=python3 PYOM_LIB=pyOM_code_py3.so PYOM_MPI_LIB=pyOM_code_MPI_py3.so

matrix:
  allow_failures:
    - env: PYTHON_EXEC=python3 PYOM_LIB=pyOM_code_py3.so PYOM_MPI_LIB=pyOM_code_MPI_py3.so

script:
- docker run -e "BH_STACK=openmp" -t veros $PYTHON_EXEC $TEST_DIR/run_tests.py /pyOM2/py_src/$PYOM_LIB
- docker run -e "BH_STACK=opencl" -t veros $PYTHON_EXEC $TEST_DIR/run_tests.py /pyOM2/py_src/$PYOM_LIB

notifications:
  email: false
