services:
  - docker

git:
  lfs_skip_smudge: true

language: python

branches:
  only:
    - master

before_install:
  - docker pull veros/ubuntu:16.04

install:
  - docker build -t veros -f package/docker/testing.dockerfile .

env:
  global:
    - PYOM_DIR=/pyOM2/py_src
    - TEST_DIR=/veros/test
  matrix:
    - BACKEND=numpy PYTHON_EXEC=python2 PYOM_LIB=pyOM_code_py2.so PYOM_MPI_LIB=pyOM_code_MPI_py2.so
    - BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=python2 PYOM_LIB=pyOM_code_py2.so PYOM_MPI_LIB=pyOM_code_MPI_py2.so
    - BACKEND=bohrium BH_STACK=opencl PYTHON_EXEC=python2 PYOM_LIB=pyOM_code_py2.so PYOM_MPI_LIB=pyOM_code_MPI_py2.so
    - BACKEND=numpy PYTHON_EXEC=python3 PYOM_LIB=pyOM_code_py3.so PYOM_MPI_LIB=pyOM_code_MPI_py3.so
    - BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=python3 PYOM_LIB=pyOM_code_py3.so PYOM_MPI_LIB=pyOM_code_MPI_py3.so
    - BACKEND=bohrium BH_STACK=opencl PYTHON_EXEC=python3 PYOM_LIB=pyOM_code_py3.so PYOM_MPI_LIB=pyOM_code_MPI_py3.so

script:
- docker run -e BH_STACK -t veros $PYTHON_EXEC $TEST_DIR/run_tests.py /pyOM2/py_src/$PYOM_LIB -b $BACKEND

notifications:
  email: false
