name: veros
channels:
  - conda-forge
  - bohrium
dependencies:
  - python==2.7
  - numpy>=1.13
  - bohrium
  - pyamg
  - click
  - requests
  - scipy
  - netCDF4
  - h5py
  - pillow
  - ruamel.yaml
  - backports.functools_lru_cache
  - future
