package:
  name: veros
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/dionhaefner/veros.git

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - openblas
    - scipy

about:
  home: https://veros.readthedocs.io
  license: MIT
  summary: "The versatile ocean simulator, in pure Python, powered by Bohrium."

extra:
  maintainers:
    - Dion Häfner <mail@dionhaefner.de>
