[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38', 'py39']


[tool.pytest.ini_options]
testpaths = [
    "test",
]
addopts = "--forked"


[build-system]
requires = ["setuptools>=40.8.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"
